### ISSUE TITLE
Pawn Transformation IllegalArgumentException

### ISSUE THREAD

**Issue by jcgruenhage** [jcgruenhage/Chess#2]
IllegalArgumentException is thrown, when a Pawn reaches the other side of the Board, instead of Transforming it into another Figure.
Should be very easy to fix.

**Comment by jcgruenhage** [comment]
``` java
Pawn from F7 to F8; Turn 215
  -----------------------------------------
8 |    |    |    |    |    | Pw |    |    |
  -----------------------------------------
7 |    | Nw |    | Kb |    |    | Bb |    |
  -----------------------------------------
6 |    | Pw |    |    | Pw |    |    |    |
  -----------------------------------------
5 |    |    |    |    |    |    |    | Pb |
  -----------------------------------------
4 |    |    |    |    |    |    |    | Pw |
  -----------------------------------------
3 |    |    | Pb |    |    |    |    |    |
  -----------------------------------------
2 |    |    |    |    | Kw |    |    |    |
  -----------------------------------------
1 |    |    |    |    |    |    |    | Nb |
  -----------------------------------------
     A    B    C    D    E    F    G    H  

King from E8 to D7; Turn 216
Exception in thread "main" java.lang.IllegalArgumentException
    at edu.gymneureut.informatik.rattenschach.model.Field.<init>(Field.java:16)
    at edu.gymneureut.informatik.rattenschach.model.figures.Pawn.getPossibleMoves(Pawn.java:63)
    at edu.gymneureut.informatik.rattenschach.model.Player.move(Player.java:160)
    at edu.gymneureut.informatik.rattenschach.model.Game.act(Game.java:120)
    at edu.gymneureut.informatik.rattenschach.model.Game.play(Game.java:101)
    at edu.gymneureut.informatik.rattenschach.control.Main.main(Main.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1
```

**Comment by jcgruenhage** [comment]
Seems fixed.

**Comment by jcgruenhage** [comment]
Is still not fixed, in some rare cases, I don't know what causes this yet, the Pawn does not get transformed resulting in an exception, when it tries to walk on.

**Comment by jcgruenhage** [comment]
fixed now
