### ISSUE TITLE
Nullpointer Exception in possibleCastlings method

### ISSUE THREAD

**Issue by jcgruenhage** [jcgruenhage/Chess#3]
``` java
Bishop from A3 to B4; Turn 63
  -----------------------------------------
8 |    |    |    | Rb |    |    | Kb | Rb |
  -----------------------------------------
7 |    |    |    |    |    | Pb | Nw | Pb |
  -----------------------------------------
6 |    | Pb | Pb |    |    |    | Pb | Nb |
  -----------------------------------------
5 |    | Pb |    |    | Pw | Pw |    | Qw |
  -----------------------------------------
4 |    | Bw | Pw | Pb |    |    |    |    |
  -----------------------------------------
3 |    |    |    |    |    |    |    | Pw |
  -----------------------------------------
2 |    |    |    | Pb | Bw |    |    |    |
  -----------------------------------------
1 | Rw | Nw |    |    |    |    |    | Rw |
  -----------------------------------------
     A    B    C    D    E    F    G    H  

Pawn from E3 to D2; Turn 64
Exception in thread "main" java.lang.NullPointerException
    at edu.gymneureut.informatik.rattenschach.model.turns.Castling.possibleCastlings(Castling.java:68)
    at edu.gymneureut.informatik.rattenschach.model.Player.move(Player.java:188)
    at edu.gymneureut.informatik.rattenschach.model.Game.act(Game.java:120)
    at edu.gymneureut.informatik.rattenschach.model.Game.play(Game.java:101)
    at edu.gymneureut.informatik.rattenschach.control.Main.main(Main.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1
```

**Comment by jcgruenhage** [comment]
Not appearing anymore
