### ISSUE TITLE
ConcurrentModificationException in RandomController

### ISSUE THREAD

**Issue by jcgruenhage** [jcgruenhage/Chess#4]
``` java
Bishop from F8 to D6; Turn 121
  -----------------------------------------
8 | Rb |    |    |    | Kb |    |    | Rb |
  -----------------------------------------
7 |    |    | Nb |    |    |    |    |    |
  -----------------------------------------
6 |    | Qb |    | Bb |    |    | Pb | Pb |
  -----------------------------------------
5 | Pb | Pb |    | Pb | Pb | Pb |    |    |
  -----------------------------------------
4 |    |    | Pw | Nw | Pw | Bw | Bb | Pw |
  -----------------------------------------
3 | Pw | Pw |    | Qw |    | Pw | Nw |    |
  -----------------------------------------
2 |    |    |    |    |    |    | Pw |    |
  -----------------------------------------
1 |    |    | Rw |    | Kw | Bw |    | Rw |
  -----------------------------------------
     A    B    C    D    E    F    G    H  

Rook from B1 to C1; Turn 122
Exception in thread "main" java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
    at java.util.LinkedList$ListItr.next(LinkedList.java:888)
    at edu.gymneureut.informatik.rattenschach.control.controller.RandomController.pickMove(RandomController.java:26)
    at edu.gymneureut.informatik.rattenschach.model.Player.measureChooseTime(Player.java:199)
    at edu.gymneureut.informatik.rattenschach.model.Player.move(Player.java:189)
    at edu.gymneureut.informatik.rattenschach.model.Game.act(Game.java:120)
    at edu.gymneureut.informatik.rattenschach.model.Game.play(Game.java:101)
    at edu.gymneureut.informatik.rattenschach.control.Main.main(Main.java:29)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1
```

**Comment by jcgruenhage** [comment]
Should be fixed.
